apiVersion: v2
kubeVersion: ">=1.19.0-0"
description: The greptimedb-operator Helm chart for Kubernetes
name: greptimedb-operator
appVersion: v0.1.0-alpha.1
type: application
home: https://github.com/GreptimeTeam/greptimedb-operator
sources:
  - https://github.com/GreptimeTeam/greptimedb-operator
keywords:
  - operator
  - database
  - greptimedb
maintainers:
- name: davider.li
  email: liyang@greptime.com
- name: zyy17
  email: zyy@greptime.com
version: v0.1.0-alpha.1
